version: "3"
services:
  chrome:
    image: selenium/standalone-chrome-debug
    expose:
      - 4444
    ports:
      - 5900
    shm_size: "2g"
    volumes:
      - /dev/shm:/dev/shm
  firefox:
    image: selenium/standalone-firefox-debug
    expose:
      - 4444
    ports:
      - 5901
    shm_size: "2g"
    volumes:
      - /dev/shm:/dev/shm
  test_suites:
    image: ${DOCKER_IMAGE}:${ENV_VERSION}
    depends_on:
      - chrome
      - firefox
    entrypoint: ["/tmp/entrypoint.sh", "${TEST_SUITES}", "${DOCKER_RUN}"]
    volumes:
    - ./test-output:/test-output